In [1]:
import pandas as pd

df = pd.read_csv('featureeng.csv')

df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion
2,36,113811,11,1,6,Web Developer,PhD,Chicago,Got Promotion
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion

# Feature Encoding

Label Encoding: converts categorical labels into numbers.

Example: "Yes" → 1, "No" → 0

You now have a numeric column Promotion Enc that models can understand.

In [2]:
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

label_encoder = LabelEncoder()

df_encoded["Promotion Enc"] = label_encoder.fit_transform(df_encoded["Promotion"])

df_encoded.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion,Promotion Enc
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion,0
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion,1
2,36,113811,11,1,6,Web Developer,PhD,Chicago,Got Promotion,0
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion,1
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion,1

# Label Encoding

Instead of using LabelEncoder, you manually assign numbers to categories.

Example:

High School → 0

Bachelor's → 1

Master’s → 2

PhD → 3

This is useful when the categories have an inherent order (ordinal features).

In [3]:
education_encoded_dict = {'High School':0,"Bachelor's":1,"Master's":2,'PhD':3}

df_encoded["Education_Enc"] = df_encoded["Education"].map(education_encoded_dict)

df_encoded.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion,Promotion Enc,Education_Enc
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion,0,0
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion,1,2
2,36,113811,11,1,6,Web Developer,PhD,Chicago,Got Promotion,0,3
3,32,102160,2,2,6,Data Engineer,High School,Austin,No Promotion,1,0
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,No Promotion,1,1

# One Hot Encoding

One-Hot Encoding → creates binary columns for each category.

Example: If City has ['Kathmandu', 'Pokhara'] → you get:

City_Kathmandu → 1 if city is Kathmandu, 0 otherwise

City_Pokhara → 1 if city is Pokhara, 0 otherwise

This avoids giving the model the wrong idea of order (unlike label encoding).

In [4]:
df_encoded = pd.get_dummies(df_encoded, columns = ["City"], prefix = ["City"])

df_encoded.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,Promotion,Promotion Enc,Education_Enc,City_Austin,City_Chicago,City_New York,City_San Francisco,City_Seattle
0,28,132612,9,2,1,Data Engineer,High School,Got Promotion,0,0,False,False,False,False,True
1,41,116641,8,4,3,Data Scientist,Master's,No Promotion,1,2,False,True,False,False,False
2,36,113811,11,1,6,Web Developer,PhD,Got Promotion,0,3,False,True,False,False,False
3,32,102160,2,2,6,Data Engineer,High School,No Promotion,1,0,True,False,False,False,False
4,29,101313,7,4,7,Product Manager,Bachelor's,No Promotion,1,1,False,False,False,True,False

# Frequency Encoding

Frequency Encoding → replaces each category with how often it appears in the dataset.

Example:

If "Data Analyst" appears 10 times, "Manager" 5 times:

"Data Analyst" → 10

"Manager" → 5

Useful for high-cardinality features (many unique values) to give the model some idea of importance.

In [5]:
job_title_counts = df_encoded["JobTitle"].value_counts().to_dict()

df_encoded["JobTitle_Enc"] = df_encoded["JobTitle"].map(job_title_counts)

df_encoded.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,Promotion,Promotion Enc,Education_Enc,City_Austin,City_Chicago,City_New York,City_San Francisco,City_Seattle,JobTitle_Enc
0,28,132612,9,2,1,Data Engineer,High School,Got Promotion,0,0,False,False,False,False,True,4
1,41,116641,8,4,3,Data Scientist,Master's,No Promotion,1,2,False,True,False,False,False,5
2,36,113811,11,1,6,Web Developer,PhD,Got Promotion,0,3,False,True,False,False,False,4
3,32,102160,2,2,6,Data Engineer,High School,No Promotion,1,0,True,False,False,False,False,4
4,29,101313,7,4,7,Product Manager,Bachelor's,No Promotion,1,1,False,False,False,True,False,3

# Target Encoding

Target Encoding → replaces a category with average of the target variable for that category.

Example:

Suppose Promotion Enc (Yes=1, No=0) looks like this:

High School: 0.2  # 20% got promoted
Bachelor's: 0.5
Master's: 0.6
PhD: 0.8

Then Education_Target_Enc column will have these numbers instead of strings.

In [6]:
education_target = df_encoded.groupby("Education")["Promotion Enc"].mean().to_dict()

df_encoded["Education_Target_Enc"] = df_encoded["Education"].map(education_target)

df_encoded.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,Promotion,Promotion Enc,Education_Enc,City_Austin,City_Chicago,City_New York,City_San Francisco,City_Seattle,JobTitle_Enc,Education_Target_Enc
0,28,132612,9,2,1,Data Engineer,High School,Got Promotion,0,0,False,False,False,False,True,4,0.75
1,41,116641,8,4,3,Data Scientist,Master's,No Promotion,1,2,False,True,False,False,False,5,0.50
2,36,113811,11,1,6,Web Developer,PhD,Got Promotion,0,3,False,True,False,False,False,4,0.00
3,32,102160,2,2,6,Data Engineer,High School,No Promotion,1,0,True,False,False,False,False,4,0.75
4,29,101313,7,4,7,Product Manager,Bachelor's,No Promotion,1,1,False,False,False,True,False,3,0.80